Update console error of Uncaught TypeError: $ is not a function
I have updated JS file which gives error "Uncaught TypeError: $ is not a function" because of DOM not ready.